name: Go Automate

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  run-automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run automate script
        env:
          API_URL: ${{ secrets.API_URL }}
          LOG_URL: ${{ secrets.LOG_API_URL }}
          ORIGIN: ${{ secrets.ORIGIN }}
        run: |
          go mod tidy
          go run automate.go
